language: ruby
rvm:
  - 2.7.1

env:
  global:
    - "CHECK='rake'"
script: "bundle exec $CHECK"

services:
  - postgresql

bundler_args: --without development --deployment --jobs=3 --retry=3

before_script:
  - cp -f config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:setup
  - mkdir -p tmp/pids

gemfile:
  - Gemfile

cache: bundler
