language: ruby
rvm:
  - 2.7.1

env:
  global:
    - "CHECK='rake'"
script: "bundle exec $CHECK"

addons:
  postgresql: "12.3"

services:
  - postgresql

bundler_args: --without development --deployment --jobs=3 --retry=3

before_script:
  # rails setup
  - psql -c 'create database app_test;' -U postgres
  - bundle exec rake db:setup
  - mkdir -p tmp/pids

gemfile:
  - Gemfile

cache: bundler