version: "3.5"
services:
  postgresql:
    image: postgres:12.3
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - 5430:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: ./config/docker/start.sh
    volumes:
      - .:/app
      - bundle:/bundle
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh/known_hosts:/etc/ssh/ssh_known_hosts
    ports:
      - "3008:3000"
    env_file:
      - ./.env
    depends_on:
      - postgresql

volumes:
  pgdata:
    driver: local
  bundle:
    driver: local
